[package]
name = "crust"
version = "0.1.0"
edition = "2024"
authors = ["Ryan Campbell <ryan.campbell4@gmail.com"]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
thiserror = "2.0.17"
